#!/bin/bash

set -o errexit
set -o nounset

{
  # Send data to the pipe immediately, which causes xargs to
  # immediately trigger the first run.
  echo 1

  # Start fswatch, which feeds all future file change events
  # into the same pipe.
  fswatch --recursive -o benchmarks cli engine search

} | \
xargs -n1 -I{} /bin/bash -c "
  cmake --build --preset debug && ctest --preset debug"
