#!/bin/bash

set -o errexit
set -o nounset

fswatch -o ./*.cc ./*.h BUILD | \
  xargs -n1 -I{} bazel test ... \
    -c opt \
    --test_output=streamed \
    --test_arg=--gtest_color=yes \
    --test_arg=--gtest_fail_if_no_test_linked
