cc_library(
    name = "display",
    srcs = [],
    hdrs = ["display.h"],
    visibility = [
        "//cli:__subpackages__",
    ],
    deps = [
        "//:perft",
        "//:position",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "perft",
    srcs = [],
    hdrs = ["perft.h"],
    visibility = [
        "//cli:__subpackages__",
    ],
    deps = [
        "//:perft",
        "//:position",
        "@abseil-cpp//absl/strings",
    ],
)

cc_library(
    name = "position",
    srcs = [],
    hdrs = ["position.h"],
    visibility = [
        "//cli:__subpackages__",
    ],
    deps = [
        "//:perft",
        "//:position",
        "@abseil-cpp//absl/strings",
    ],
)
